---

- hosts: all
  become: true
  tasks:

  - name: Upgrade all packages
    ansible.builtin.yum:
      name: '*'
      state: latest
 
  - name: install a list of packages with a list variable
    ansible.builtin.yum:
      name: "{{ packages }}"
    vars:
      packages:
      - httpd
      - httpd-tools
         

